import Rhino
import scriptcontext
import rhinoscriptsyntax as rs
from SolidPolygon101 import WallShape

wallContour = rs.GetObjects ( None, 4, True, False, False, None, 1, 0, None )

if len(wallContour)>1:
    wallContour = rs.JoinCurves ( wallContour, False, None )

## Analyses
for i in wallContour:
    planar = rs.IsCurvePlanar (i, segment_index=-1) 
    closed = rs.IsCurveClosed (i)
if planar and closed :
    wallThickness = rs.GetReal ( "Wall thickness", number=None, minimum=None, maximum=None )
    create = WallShape(wallThickness,wallContour)
    walls = create.AddWall()
else:
    print "Curve needs to be a closed and planar curve." 

